import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../../services/lost_found_api.dart';

class LostFoundScreen extends StatefulWidget { const LostFoundScreen({super.key}); @override State<LostFoundScreen> createState()=>_LostFoundScreenState(); }
class _LostFoundScreenState extends State<LostFoundScreen> with SingleTickerProviderStateMixin {
  Map<String,dynamic> _cap={}; List<dynamic> _found=[]; List<dynamic> _lost=[]; List<dynamic> _claims=[]; bool _loading=true; String? _error; late TabController _tabs;
  @override void initState(){super.initState();_tabs=TabController(length:3,vsync:this);_load();}
  @override void dispose(){_tabs.dispose();super.dispose();}
  bool get _manager=>_cap['can_manage']==true; bool get _family=>_cap['can_claim']==true;
  Future<void> _load() async {setState(()=>_loading=true);try{final c=await LostFoundApi.capabilities();final f=await LostFoundApi.items(entryType:'found');final l=await LostFoundApi.items(entryType:'lost');final cl=c['can_claim']==true?await LostFoundApi.myClaims():<dynamic>[];if(mounted)setState(()=>{_cap=c,_found=f,_lost=l,_claims=cl,_error=null});}catch(e){if(mounted)setState(()=>_error=e.toString());}finally{if(mounted)setState(()=>_loading=false);}}
  Future<void> _openCreate(String type) async {final result=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,useSafeArea:true,builder:(ctx)=>_LostFoundForm(cap:_cap,type:type));if(result==true){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(type=='found'?'Found item added.':'Lost item reported.')));await _load();}}
  Future<void> _claim(Map item) async {final students=List<dynamic>.from(_cap['students']??[]);if(students.isEmpty)return;int studentId=int.tryParse('${students.first['id']}')??0;final note=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:Text('Claim ${item['title']??'item'}'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[if(students.length>1)DropdownButtonFormField<int>(value:studentId,items:students.map((s)=>DropdownMenuItem<int>(value:int.tryParse('${s['id']}'),child:Text('${s['name']}'))).toList(),onChanged:(v)=>studentId=v??studentId,decoration:const InputDecoration(labelText:'Student')),const SizedBox(height:12),TextField(controller:note,maxLines:3,decoration:const InputDecoration(labelText:'How can school verify ownership?',border:OutlineInputBorder()))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Send Claim'))]));if(ok==true){try{await LostFoundApi.claim(int.parse('${item['id']}'),studentId:studentId,note:note.text);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Claim sent for school verification.')));await _load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}}
  Future<void> _matches(Map item) async {try{final list=await LostFoundApi.matches(int.parse('${item['id']}'));if(!mounted)return;showModalBottomSheet(context:context,isScrollControlled:true,builder:(ctx)=>SafeArea(child:Padding(padding:const EdgeInsets.all(16),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Possible Matches',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('These are suggestions only. School staff should verify ownership before handover.',style:TextStyle(color:Colors.orange)),const SizedBox(height:12),if(list.isEmpty)const Padding(padding:EdgeInsets.all(20),child:Text('No strong match found yet.')),for(final m in list.take(5))ListTile(contentPadding:EdgeInsets.zero,leading:CircleAvatar(child:Text('${m['score']??0}%')),title:Text('${m['item']?['title']??''}'),subtitle:Text('${m['item']?['item_code']??''} • ${m['item']?['location']??''}'))]))));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
  @override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Text('Lost & Found'),bottom:TabBar(controller:_tabs,tabs:const[Tab(text:'Found'),Tab(text:'Lost'),Tab(text:'My Claims')])),floatingActionButton:(_manager||_family)?FloatingActionButton.extended(onPressed:()=>_openCreate(_manager?'found':'lost'),icon:const Icon(Icons.add),label:Text(_manager?'Add Found':'Report Lost')):null,body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?Center(child:Padding(padding:const EdgeInsets.all(20),child:Text(_error!,textAlign:TextAlign.center))):RefreshIndicator(onRefresh:_load,child:TabBarView(controller:_tabs,children:[_ItemsList(items:_found,family:_family,onClaim:_claim),_ItemsList(items:_lost,family:false,onMatch:_matches),_ClaimsList(claims:_claims,family:_family)])) );}
}

class _ItemsList extends StatelessWidget { final List<dynamic> items; final bool family; final Future<void> Function(Map)? onClaim; final Future<void> Function(Map)? onMatch; const _ItemsList({required this.items,required this.family,this.onClaim,this.onMatch});
 @override Widget build(BuildContext context){if(items.isEmpty)return ListView(children:const[Padding(padding:EdgeInsets.all(32),child:Center(child:Text('Nothing here right now.')))]);return ListView.builder(padding:const EdgeInsets.all(12),itemCount:items.length,itemBuilder:(ctx,i){final item=Map<String,dynamic>.from(items[i]);return Card(clipBehavior:Clip.antiAlias,margin:const EdgeInsets.only(bottom:12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(item['has_image']==true)_SecureLostFoundImage(id:int.parse('${item['id']}')),Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('${item['title']??''}',style:const TextStyle(fontSize:17,fontWeight:FontWeight.w700))),_StatusChip('${item['status']??''}')]),const SizedBox(height:4),Text('${item['item_code']??''} • ${item['category']??''}',style:TextStyle(color:Colors.grey.shade600)),const SizedBox(height:6),Text('${item['event_date']??''}${('${item['location']??''}').trim().isNotEmpty?' • ${item['location']}':''}'),if(('${item['description']??''}').trim().isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:Text('${item['description']}')),const SizedBox(height:10),if(family&&['open','claim_pending'].contains(item['status']))FilledButton.icon(onPressed:()=>onClaim?.call(item),icon:const Icon(Icons.back_hand_outlined),label:const Text('This may be mine')),if(onMatch!=null)OutlinedButton.icon(onPressed:()=>onMatch?.call(item),icon:const Icon(Icons.auto_awesome),label:const Text('Possible matches'))]))]));});}}
class _SecureLostFoundImage extends StatefulWidget {final int id;const _SecureLostFoundImage({required this.id});@override State<_SecureLostFoundImage> createState()=>_SecureLostFoundImageState();}
class _SecureLostFoundImageState extends State<_SecureLostFoundImage>{Uint8List? b;@override void initState(){super.initState();LostFoundApi.imageBytes(widget.id).then((x){if(mounted)setState(()=>b=x);}).catchError((_){ });}@override Widget build(BuildContext context)=>SizedBox(height:190,width:double.infinity,child:b==null?Container(color:Colors.grey.shade100,child:const Center(child:Icon(Icons.image_outlined,size:42))):Image.memory(b!,fit:BoxFit.cover));}
class _StatusChip extends StatelessWidget{final String status;const _StatusChip(this.status);@override Widget build(BuildContext context)=>Chip(label:Text(status.replaceAll('_',' '),style:const TextStyle(fontSize:11)),visualDensity:VisualDensity.compact);}
class _ClaimsList extends StatelessWidget{final List<dynamic> claims;final bool family;const _ClaimsList({required this.claims,required this.family});@override Widget build(BuildContext context){if(!family)return ListView(children:const[Padding(padding:EdgeInsets.all(32),child:Center(child:Text('Claims are managed from the school web panel.')))]);if(claims.isEmpty)return ListView(children:const[Padding(padding:EdgeInsets.all(32),child:Center(child:Text('No claims submitted yet.')))]);return ListView(padding:const EdgeInsets.all(12),children:claims.map((c)=>Card(child:ListTile(title:Text('${c['item']?['title']??''}'),subtitle:Text('${c['item']?['item_code']??''}${c['review_note']!=null?'\nSchool: ${c['review_note']}':''}'),trailing:_StatusChip('${c['status']??''}')))).toList());}}

class _LostFoundForm extends StatefulWidget{final Map<String,dynamic> cap;final String type;const _LostFoundForm({required this.cap,required this.type});@override State<_LostFoundForm> createState()=>_LostFoundFormState();}
class _LostFoundFormState extends State<_LostFoundForm>{final title=TextEditingController(),location=TextEditingController(),color=TextEditingController(),brand=TextEditingController(),description=TextEditingController(),privateDetail=TextEditingController();String? imagePath;String category='Other';String date=DateTime.now().toIso8601String().slice(0,10);int? studentId;bool saving=false;
 @override void initState(){super.initState();final cats=List<dynamic>.from(widget.cap['categories']??[]);if(cats.isNotEmpty)category='${cats.first}';final students=List<dynamic>.from(widget.cap['students']??[]);if(students.isNotEmpty)studentId=int.tryParse('${students.first['id']}');}
 Future<void> pickGallery() async {final x=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:88,maxWidth:1800);if(x!=null)setState(()=>imagePath=x.path);}
 Future<void> save() async {if(title.text.trim().isEmpty)return;setState(()=>saving=true);try{await LostFoundApi.createItem(fields:{'entry_type':widget.type,'title':title.text.trim(),'category':category,'event_date':date,'location':location.text.trim(),'color':color.text.trim(),'brand':brand.text.trim(),'description':description.text.trim(),if(studentId!=null)'student_id':'$studentId',if(widget.cap['can_manage']==true)'private_identifying_detail':privateDetail.text.trim()},imagePath:imagePath);if(mounted)Navigator.pop(context,true);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>saving=false);}}
 @override Widget build(BuildContext context){final cats=List<dynamic>.from(widget.cap['categories']??[]);final students=List<dynamic>.from(widget.cap['students']??[]);return Padding(padding:EdgeInsets.only(left:16,right:16,top:14,bottom:MediaQuery.of(context).viewInsets.bottom+20),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.type=='found'?'Add Found Item':'Report Lost Item',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Colors.blue.shade50,borderRadius:BorderRadius.circular(8)),child:const Row(children:[Icon(Icons.photo_library_outlined),SizedBox(width:8),Expanded(child:Text('Photo selection uses Gallery only. No direct camera permission is requested.'))])),const SizedBox(height:12),TextField(controller:title,decoration:const InputDecoration(labelText:'Item title *',border:OutlineInputBorder())),const SizedBox(height:10),DropdownButtonFormField<String>(value:category,items:cats.map((c)=>DropdownMenuItem(value:'$c',child:Text('$c'))).toList(),onChanged:(v)=>setState(()=>category=v??'Other'),decoration:const InputDecoration(labelText:'Category',border:OutlineInputBorder())),if(widget.type=='lost'&&students.isNotEmpty)...[const SizedBox(height:10),DropdownButtonFormField<int>(value:studentId,items:students.map((s)=>DropdownMenuItem<int>(value:int.tryParse('${s['id']}'),child:Text('${s['name']}'))).toList(),onChanged:(v)=>setState(()=>studentId=v),decoration:const InputDecoration(labelText:'Student',border:OutlineInputBorder()))],const SizedBox(height:10),TextField(controller:location,decoration:const InputDecoration(labelText:'Location',border:OutlineInputBorder())),const SizedBox(height:10),Row(children:[Expanded(child:TextField(controller:color,decoration:const InputDecoration(labelText:'Color',border:OutlineInputBorder()))),const SizedBox(width:10),Expanded(child:TextField(controller:brand,decoration:const InputDecoration(labelText:'Brand',border:OutlineInputBorder())))]),const SizedBox(height:10),TextField(controller:description,maxLines:3,decoration:const InputDecoration(labelText:'Description',border:OutlineInputBorder())),if(widget.type=='found'&&widget.cap['can_manage']==true)...[const SizedBox(height:10),TextField(controller:privateDetail,decoration:const InputDecoration(labelText:'Private ownership verification detail',helperText:'Hidden from students/parents',border:OutlineInputBorder()))],const SizedBox(height:12),OutlinedButton.icon(onPressed:pickGallery,icon:const Icon(Icons.photo_library),label:Text(imagePath==null?'Choose photo from Gallery':'Photo selected — change')),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton(onPressed:saving?null:save,child:Text(saving?'Saving...':'Save')))])) );}}
extension _StringSlice on String{String slice(int start,int end)=>substring(start,end);}
