// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhLPCQeeFkI2yD5p1m3srmGCoUY-HirR4',
    appId: '1:667315534601:web:88374444bfed568d7ab1d8',
    messagingSenderId: '667315534601',
    projectId: 'schoolerp-143ea',
    authDomain: 'schoolerp-143ea.firebaseapp.com',
    storageBucket: 'schoolerp-143ea.firebasestorage.app',
    measurementId: 'G-BKD8C7X90K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6h5jlZ1DJbGulpsxFY9JDLOfsBsl8XJU',
    appId: '1:667315534601:android:f0d55dfb9c331e7b7ab1d8',
    messagingSenderId: '667315534601',
    projectId: 'schoolerp-143ea',
    storageBucket: 'schoolerp-143ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYB3dxSBfzyHCsjcNjhI-pa97aWRZC8nU',
    appId: '1:667315534601:ios:f43ce8d1ee627c2c7ab1d8',
    messagingSenderId: '667315534601',
    projectId: 'schoolerp-143ea',
    storageBucket: 'schoolerp-143ea.firebasestorage.app',
    iosClientId: '667315534601-fk2skpfe5s2j58eq026bvffm8oeg1juk.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYB3dxSBfzyHCsjcNjhI-pa97aWRZC8nU',
    appId: '1:667315534601:ios:f43ce8d1ee627c2c7ab1d8',
    messagingSenderId: '667315534601',
    projectId: 'schoolerp-143ea',
    storageBucket: 'schoolerp-143ea.firebasestorage.app',
    iosClientId: '667315534601-fk2skpfe5s2j58eq026bvffm8oeg1juk.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhLPCQeeFkI2yD5p1m3srmGCoUY-HirR4',
    appId: '1:667315534601:web:d512f75e9f821ab47ab1d8',
    messagingSenderId: '667315534601',
    projectId: 'schoolerp-143ea',
    authDomain: 'schoolerp-143ea.firebaseapp.com',
    storageBucket: 'schoolerp-143ea.firebasestorage.app',
    measurementId: 'G-GRM7C17K88',
  );
}
